### ISSUE TITLE
SQL Queries for Python Connection

### ISSUE THREAD

**Issue by cethorne** [tessa-hudson/Capstone_Fall2021#16]
SQL code needed for:

- searching for a specific attendee
- attendees in a specific group
- groups in an event
- attendee points for a specific attendee
- the pointlog for a specific event

**Comment by tessa-hudson** [comment]
I currently need listing all attendees, creating a new attendee, getting a specific attendee, and deleting an attendee. Same for groups.

**Comment by tessa-hudson** [comment]
Deleting can be pushed off for now if needed. It's not currently implemented on the frontend, but I do have an endpoint set up for it

**Comment by trblair16** [comment]
I am also going to add:

- Getting a specific group by id
- Getting a specific event by id
- Getting attendees for an event by event id
